language: java
jdk:
  - openjdk8
variables:
  - GRADLE_OPTS="-Dorg.gradle.daemon=false"
install:
  - ./gradlew -b gradle/bootstrap.gradle -PprojectsDirName='' bootstrap
script:
  - ./gradlew -p test test
  - git describe --tags > VERSION.txt
  - rm -rf .gradle gradle/.gradle .git* .travis.yml test
  - mkdir projects
  - zip -r teamscale-client-gradle.zip .
deploy:
  provider: releases
  api_key:
    secure: WWYdG/iLwU2cJi06ObwVLLg4pCE7BYxnpJvPCgnqxxbWUiJNPWYBWSZq0G81vHVy79XYduStrVztyqcd5BfXrX81TetIDyrFbEIl8NQW8ZMEppVsHGd3MNcbRwSChHrzZaJZqonUMSw5SL4gnUTRWCEKSm5Z+bPVR43ny0CPnmiPr8F2MkeQcMa4bF+elP1K6SyKIcl1xxIOJcGYJpYo8nOCA5uDC7zfbkFUN9FFH8m0OhPZtYavPg9GqCOjPKavhI5dO9bp0DJBxqQiU20GeUOUm1nY+mTF21hDgvdOZB/WrrIlKaSqwGTYRHLZ+LxBEg0e+CMuAz2pm/ADnN/ePAV+XxDerpm8bmoDbCismrOLA1wBG5W4lFhNv/LVsm9KmZ/R626JD75Snm43Vno79AzGeOOnVR6vWSoDwzgk3gp7TrYAHH+4Jrwmi7wyRoe7HTTixhA/8mnLEgVzSQ/HWd3DHzjO4SUKZsXuDgRezy5VAKZ2p5VTUjKS7jOXTSY9m+j68/VJaDnwrQExB96kTjhpNaRKWdOMlZV0xifAhAPgaxfT1z7ygIEJKNPav5cF7wS0Qa4eIJh1F3dl2TogGF9MKreNUFGAgwgdi+XIzGXp8q+DQvgm6ZyHg1F1+3GYok2LJD5wA4VkiGu5WmiYOQq+xKdFHNX/dzSuUpfodIQ=
  skip_cleanup: true
  file: teamscale-client-gradle.zip
  on:
    repo: cqse/teamscale-client-gradle
    tags: true
